controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /login

super_admin_users_controllers:
    prefix: '/super-admin/users-prueba'
    resource:
        path: ../src/Controller/SuperAdmin/Users/
        namespace: App\Controller\SuperAdmin\Users
    type: attribute

admin_controllers:
    prefix: '/admin'
    resource:
        path: ../src/Controller/Admin/
        namespace: App\Controller\Admin
    type: attribute
