@montisgal_events_api_HostAddress = http://localhost:5165/api

GET {{montisgal_events_api_HostAddress}}/event/
Accept: application/json

###

POST {{montisgal_events_api_HostAddress}}/event/
Accept: application/json
Content-Type: application/json

{
  "id": "dbb7b5f7-e6e0-4d3b-a96e-bcf3902211b3",
  "name": "name",
  "description": "apuff"
}

###
